package ms.notification.dynamo.repository.model;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
 

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data
@DynamoDBTable(tableName = "message")
@Builder
@NoArgsConstructor
@AllArgsConstructor 
public class Email {
	
	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey 
	private String id;
	
	@DynamoDBAttribute
	private String entityType;

	@DynamoDBAttribute
	private String from;

	@DynamoDBAttribute
	private String to;

	@DynamoDBAttribute
	private String content;

	@DynamoDBAttribute
	private String subject;

	@DynamoDBAttribute
	private String status;

	@DynamoDBAttribute
	private Date createDate;

	@DynamoDBAttribute
	private Date sentDate;
 

	
	
}
