version = 0.1
[default.deploy.parameters]
stack_name = "notification-ms"
resolve_s3 = true
s3_prefix = "notification-ms"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
