AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless - norification-ms
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  NotificationFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: .
      Handler: ms.notification.StreamLambdaHandler::handleRequest
      Runtime: java21
      SnapStart:
        ApplyOn: PublishedVersions

      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Environment: 
        Variables:
          PARAM1: VALUE
 
      Timeout: 30
      Events:
        GetResource:
          Type: Api 
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  NotificationFunctionApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod'


 