---
openapi: 3.1.0
info:
  title: Generated API
  version: "1.0"
paths:
  /auth/login:
    post:
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
        required: true
      responses:
        "200":
          description: OK
  /auth/register:
    post:
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                displayName:
                  type: string
                password:
                  type: string
        required: true
      responses:
        "200":
          description: OK
  /users:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
  /users/me:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
  /users/{id}:
    put:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                displayName:
                  type: string
                email:
                  type: string
        required: true
      responses:
        "200":
          description: OK
    get:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
    delete:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
servers:
- url: http://localhost:8080
- url: https://localhost:8443