package ms.notification.dynamo.repository.model;

import java.util.Date;


import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data
//@DynamoDBTable(tableName = "message")
@Builder
@NoArgsConstructor
@AllArgsConstructor 
public class Message {
	
	public static final String TYPE_EMAIL = "email";
	
	//@DynamoDBHashKey
   //@DynamoDBAutoGeneratedKey 
	private String id;
	
	//@DynamoDBAttribute
	private String entityType;

	//@DynamoDBAttribute
	private String from;

	//@DynamoDBAttribute
	private String to;

	//@DynamoDBAttribute
	private String content;

	//@DynamoDBAttribute
	private String subject;

	//@DynamoDBAttribute
	private String status;

	//@DynamoDBAttribute
	private Date createDate;

	//@DynamoDBAttribute
	private Date sentDate;
 

	
	
}
